language: cpp

sudo: required

services:
- docker

env:
  matrix:
    - DOCKERBASE=flecsi-buildenv:ubuntu MINIMAL=ON MPI=OFF RUNTIME=serial
    - DOCKERBASE=flecsi_tpl:ubuntu MPI=OFF RUNTIME=legion    DOCKERHUB=true
    - DOCKERBASE=flecsi_tpl:ubuntu MPI=OFF RUNTIME=legion    WERROR=yes
    - DOCKERBASE=flecsi_tpl:ubuntu MPI=ON  RUNTIME=mpilegion DOCKERHUB= rue
    - DOCKERBASE=flecsi_tpl:ubuntu MPI=ON  RUNTIME=mpilegion WERROR=yes
    - DOCKERBASE=flecsi-buildenv:ubuntu MPI=OFF  RUNTIME=serial       DOCKERHUB=true
    - DOCKERBASE=flecsi-buildenv:ubuntu MPI=OFF  RUNTIME=serial       WERROR=yes
    - DOCKERBASE=flecsi-buildenv:ubuntu MPI=OFF  COVERAGE=ON RUNTIME=serial

    - DOCKERBASE=flecsi-buildenv:fedora MINIMAL=ON MPI=OFF RUNTIME=serial
    - DOCKERBASE=flecsi_tpl:fedora MPI=OFF RUNTIME=legion    DOCKERHUB=true
    - DOCKERBASE=flecsi_tpl:fedora MPI=OFF RUNTIME=legion    WERROR=yes
    - DOCKERBASE=flecsi_tpl:fedora MPI=ON  RUNTIME=mpilegion DOCKERHUB=true
    - DOCKERBASE=flecsi_tpl:fedora MPI=ON  RUNTIME=mpilegion WERROR=yes
    - DOCKERBASE=flecsi-buildenv:fedora MPI=OFF RUNTIME=serial        DOCKERHUB=true
    - DOCKERBASE=flecsi-buildenv:fedora MPI=OFF RUNTIME=serial        WERROR=yes
    - DOCKERBASE=flecsi-buildenv:fedora MPI=OFF RUNTIME=serial COVERAGE=ON

script:
  - cp -vr docker ${HOME}/docker
  - sed -i "1s/flecsi-buildenv:fedora/${DOCKERBASE}/" ${HOME}/docker/Dockerfile
  - cd ../../
  - mv -v ${TRAVIS_REPO_SLUG} $HOME/docker
  - cp -r $HOME/.ccache ${HOME}/docker/ccache
  - if [[ ${CC} != gcc ]]; then TAG="_${CC}"; fi
  - docker build --build-arg MPI=${MPI} --build-arg RUNTIME=${RUNTIME} --build-arg CXXFLAGS=${WERROR:+-Werror}
                --build-arg COVERAGE=${COVERAGE} --build-arg MINIMAL=${MINIMAL}
                --build-arg CC=${CC} --build-arg CXX=${CXX}
                -t flecsi/flecsi:${DOCKERBASE#*:}_${RUNTIME}${TAG} ${HOME}/docker/ &&
    rm -rf ${HOME}/.ccache &&
    CON=$(docker run -d flecsi/flecsi:${DOCKERBASE#*:}_${RUNTIME}${TAG} /bin/bash) &&
    docker cp ${CON}:/home/flecsi/.ccache ${HOME}/

after_success:
  - if [[ ${DOCKERHUB} = true && ${DOCKER_EMAIL} && ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${TRAVIS_BRANCH} == master ]]; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push "flecsi/flecsi:${DOCKERBASE#*:}_${RUNTIME}${TAG}";
    fi
  - if [[ ${TRAVIS_JOB_NUMBER} = *.1 ]]; then
      cd $HOME/docker/flecsi;
      rm -rf cinch;
      git fetch origin gh-pages && git checkout -b gh-pages FETCH_HEAD;
      mkdir -p assets;
      rm -rf assets/doxygen html;
      CON=$(docker run -d flecsi/flecsi:${DOCKERBASE#*:}_${RUNTIME}${TAG}) && docker cp ${CON}:/home/flecsi/flecsi/build/doc/doxygen/html . ;
      mv html assets/doxygen;
      git add --all assets/doxygen;
      if [[ ${TRAVIS_BRANCH} = master && ${encrypted_5669a181ba27_key} && ${encrypted_5669a181ba27_iv} && ${TRAVIS_PULL_REQUEST} == false ]]; then
        git config --global user.name "Automatic Deployment (Travis CI)";
        git config --global user.email "flecsi-commit@lanl.gov";
        git commit -m "Documentation Update";
        openssl aes-256-cbc -K $encrypted_5669a181ba27_key -iv $encrypted_5669a181ba27_iv -in deploy.enc -out ~/.ssh/id_rsa -d;
        chmod 600 ~/.ssh/id_rsa;
        git push git@github.com:${TRAVIS_REPO_SLUG} gh-pages:gh-pages;
      else
        git status;
        git diff --cached --no-color | head -n 500;
      fi;
    fi

cache:
  - ccache

compiler:
  - gcc

notifications:
  branches:
    only:
      - master
  email:
    recipients:
      secure: OzppTS3kOkp5+052T8DMtXiNmUO5OttAY01kC1lDqwdPVAQiFvrnR3iqz/AJIJk5bNsI0vbmRtCBL4PnH3aUm7CUpXN3RF7vF0vpl0PxPMc/Ms4Trsrv96jqPyoJoACRqgk6W7/pdr8OXbYTh+7u2bO9/sUaZTDT/PbH9RQdKrDa2u+uebL9s0FTo/ObZSNXRAoXmSY46gDXzWbEVO2co6ETu4eXy/Bu0wvhB4jXneA+0sv8dXAmRmvL1tsxTeAEcV2MxLlaiVPAyvpCLzt3ZRvkohAjCeQaVTTo8hP0S7YdAMwUmAcMI8NASWVh8fcaFV72IsFkg7nD2Jiv7mRt52vwqDiJLw65LN9/+ltrK142F/nFUSeB9ynPBjbpXyEMl4nsBbO9hk5io4lKYQ/EJ2WJyCPaFtuy1fR9Gzrjj/LwKPw2WrxAlrlNYlIFdMDvltTXGegheVNePDHSOc6AS/32VW4A8fZh5gUAfB96XveRj0fGegCyFdIzErZg4fiZxOEDkqeB8sxuPnX+ylKr2gWsjpfs+etjnANVsgfPMOWaIsW8K2FqVIiTEoGGELoQHEe5uzOcXgtRQSbji2U28c5pRhNHdoitODwlTMVE/3WEiQksFGztR675LlPfF15+HyjWnAS/gN5vLIqmrQoZcp1+Pbr4ebxwTcL4JSGUaPs=
